### ISSUE TITLE
PPDefModifier.dll not worked

### ISSUE THREAD

**Issue by iUkka** [Sheep-y/Modnix#3]
No errors in logs, but stats not changed.
![image](https://user-images.githubusercontent.com/5823637/75603948-b68da180-5ae4-11ea-923c-99663c668a15.png)

**Comment by Sheep-y** [comment]
May I know which PPDef are you using?

I tested `Skip Soldier Animations.json` and it works, but I got a verbal report that Weapon Overhaul is not, which I'll test soon.

**Comment by iUkka** [comment]
It was some sort of glitch or mod conflict. After some retry i receive working combination.
Sorry for issue :)
Maybe my mistake using existing save for test.
![image](https://user-images.githubusercontent.com/5823637/75604616-a2996e00-5aeb-11ea-97ce-04562a7cdae3.png)
