### ISSUE TITLE
Fails to inject

### ISSUE THREAD

**Issue by mad2342** [Sheep-y/Modnix#31]
Hi Sheep-y,

Nice to see you around PP too (know some stuff of you for HBS Battletech :-))
I believe Modnix is only meant to be used with Epic but as the Year One Edition for GOG just released, i had to try (PP really needs some UI-issues fixed..) However i get the following error when trying to patch:

```
05:43:22.2000 Thread6┊Running at E:\GOG Galaxy\Games\Phoenix Point Year One Edition\PhoenixPointWin64_Data\Managed : E:\GOG Galaxy\Games\Phoenix Point Year One Edition\PhoenixPointWin64_Data\Managed\ModnixInjector.exe /y
05:43:22.5204 Thread6┊Standard out: Modnix Injector 2.5.3.0
----------------------------
Cinemachine.dll backed up to Cinemachine.dll.orig
Injecting Cinemachine.dll with Sheepy.Modnix.ModLoader.Init at Cinemachine.CinemachineBrain.OnEnable
Found 36 IL instructions in OnEnable.
Injecting before last op IL_0086: ret
Writing back to Cinemachine.dll...
ERROR: An exception occured: System.IO.IOException: The requested operation cannot be performed on a file with a user-mapped section open.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
```
I'm not really understanding your injector code, so i thought maybe you're still active and can update for the GOG-version, too?
Thx a lot, best regards, Mad

**Comment by Sheep-y** [comment]
Wow. I added Steam support but I forgot there is a gog version.  Thanks for the reminder.

The error means something has opened the file.   Do you think it might be anti-virus?  If so perhaps I can add a timer to try for a few minutes.   If the problem persists, I'd use Unlocker, Process Explorer, or other similar tools to see what is locking the file.

**Comment by mad2342** [comment]
Hi Sheepy,
Sry to leave this issue open, i simply forgot about it. 
My issue was resolved with "standard procedures" (Verify Game, Unistall/Re-Install Modnix, Reboot).
Thank you for this excellent tool!
Best regards, Mad
