### ISSUE TITLE
Disabled: Missing requirement zy.javascript.

### ISSUE THREAD

**Issue by RunestarX** [Sheep-y/Modnix#37]
![Capture](https://user-images.githubusercontent.com/100398596/155655841-fd9d76da-73ab-49ae-ab2a-563d8a276d31.PNG)

Trying to install some of the demo mods, but something's missing.

Nevermind I figured it out. Needed modnix 3 and the javascript runtime mod.

**Comment by Sheep-y** [comment]
Glad you figured it out!
